MENUS = {
    "Sales": [
        "New Bill",
        "Hold Bill",
        "Return Bill",
        "Sales History",
        "Day End",
    ],
    "Purchase": [
        "New Purchase",
        "Purchase Return",
        "Purchase History",
        "Supplier Payment",
    ],
    "Account": [
        "Customer Receipt",
        "Cash Book",
        "Bank Book",
        "Ledger",
        "Journal Entry",
        "Account Roles",
        "Trial Balance",
        "Profit & Loss",
        "Balance Sheet",
    ],
    "Reports": [
        "Sales Report",
        "Purchase Report",
        "Stock Report",
        "Expiry Report",
        "Party Wise Report",
        "GST Report",
    ],
    "Master": [
        "Item Master",
        "Company Master",
        "Unit Master",
        "Drug Master",
        "Supplier Master",
        "Customer Master",
        "Doctor Master",
        "Category Master",
        "User Master",
        "Backup & Restore",
    ],
}
